imports:
  - config.yaml

parameters:
  daipeproject:
    databricks:
      address: 'https://adb-8406481409439422.2.azuredatabricks.net'

  dbxdeploy:
    target:
      repo:
        base_dir: '/Repos/integration/{repo_name}'
